import { Inter, JetBrains_Mono } from "next/font/google";
import type { PropsWithChildren } from "react";
import "./globals.css";
import Header from "@/components/header";

const jetbrainsMono = JetBrains_Mono({
   subsets: ["latin"],
   weight: ["100", "200", "300", "400", "500", "600", "700", "800"],
   variable: '--font-jetbrainsMono',
   display: "swap",
  });

export const metadata = {
  title: "Create Next App",
  description: "Generated by me 8D",
}

{/*npm run dev --- localhost:3000*/}
export default function RootLayout({ children }: PropsWithChildren) {
  return (
    <html lang="en" className={`dark ${jetbrainsMono.variable}`}>
      <body>
        <Header/>
        {children}
      </body>
    </html>
  );
}
